import type { MedusaProductCategory } from "@/types/medusa";
export const clothingCategories: MedusaProductCategory[] = [
  {
    id: "pcat_tops",
    name: "Tops",
    handle: "tops",
    rank: 0,
    parent_category_id: null,
    created_at: "",
    updated_at: "",
    category_children: [
      {
        id: "pcat_tshirts",
        name: "T-shirts",
        handle: "t-shirts",
        rank: 0,
        parent_category_id: "pcat_tops",
        created_at: "",
        updated_at: "",
        category_children: [],
      },
      {
        id: "pcat_shirts",
        name: "Shirts",
        handle: "shirts",
        rank: 1,
        parent_category_id: "pcat_tops",
        created_at: "",
        updated_at: "",
        category_children: [],
      },
    ],
  },
  {
    id: "pcat_bottoms",
    name: "Bottoms",
    handle: "bottoms",
    rank: 1,
    parent_category_id: null,
    created_at: "",
    updated_at: "",
    category_children: [],
  },
  {
    id: "pcat_sleepwear",
    name: "Sleepwear",
    handle: "sleepwear",
    rank: 2,
    parent_category_id: null,
    created_at: "",
    updated_at: "",
    category_children: [],
  },
];
